### ISSUE TITLE
add facebook link support

### ISSUE THREAD

**Issue by SeaSon2002** [saucesteals/previewer#1]
(almost ) all facebook links can have a simplified version by adding mbasic. before the link

example: 
[https://facebook.com/discord/photos/a.865815860152812/4561511320583229/](https://facebook.com/discord/photos/a.865815860152812/4561511320583229/)

[https://mbasic.facebook.com/discord/photos/a.865815860152812/4561511320583229/](https://mbasic.facebook.com/discord/photos/a.865815860152812/4561511320583229/)

**Comment by saucesteals** [comment]
> (almost ) all facebook links can have a simplified version by adding mbasic. before the link
> 
> example: https://facebook.com/discord/photos/a.865815860152812/4561511320583229/
> 
> https://mbasic.facebook.com/discord/photos/a.865815860152812/4561511320583229/

From my previous experience with facebook I'm fairly sure they ban IPs for pretty long if its marked as a bot (that spams to a certain point I'm guessing) so previewer may or may not have to get some kind of proxy support if we are gonna rely on getting the mobile page.

Do you know the process for getting official API access for facebook that has support for public posts/profiles data?
